on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"] 
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: ${{ hashFiles('web_app/**/*.py') != '' }}
        run: |
          cd web_app
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev --python ${{ matrix.python-version }}

      - name: Run tests with coverage
        env:
          MONGO_URI: "mongodb://localhost:27017" 
          DB_NAME: "test_db" 
          SECRET_KEY: "test_secret"
        if: ${{ hashFiles('web_app/**/*.py') != '' }}
        run: |
          cd web_app
          PYTHONPATH=. pipenv run pytest --cov=. --cov-report=term-missing tests/
  deliver:
    runs-on: ubuntu-latest
    needs: build # Change this to 'test' if you renamed your first job
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./web_app
          push: true
          tags: csl9997/reminder-web:latest
